services:
  - type: web
    name: likebetfair-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: cd server && node app.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/odds/kbo 