services:
  - type: web
    name: likebetfair-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    buildFilter:
      paths:
        - server/**
        - package.json
        - package-lock.json
    autoDeploy: true 